version: '3.4'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: py manage.py runserver 0.0.0.0:9000
    volumes:
      - .:/app
    ports:
      - "9000:9000"
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      MSSQL_USER: sa
      MSSQL_PASSWORD: Hieudeptroai666@
      MSSQL_DB: Pet_health_care_DB
    volumes:
      - db_data:/var/lib/mssql/data
    ports:
      - "1433:1433"

volumes:
  db_data: {}
